url: https://atgenomics.github.io
baseurl:

# Site settings
title: ATGenomics
email: atgenomics@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Victor Flores
  pic: "2015-07-29 20.15.28"
  position: Bioinformatician
  social:
    - title: twitter
      url: http://twitter.com/vflorelo
    - title: facebook
      url: http://facebook.com/vflorelo
    - title: stack-overflow
      url: http://stackoverflow.com/users/2649517/vflorelo

- name: Otoniel Maya
  pic: 2
  position: Bioinformatician
  social:
    - title: twitter
      url: http://twitter.com/vflorelo
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sandra Ortega
  pic: 3
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

- name: Marco Carballo
  pic: 4
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

- name: Alejandra Ch√°vez
  pic: 5
  position: Junior Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

social:
  - title: twitter
    url: http://twitter.com/atgenomics
  - title: facebook
    url: http://facebook.com/atgenomics
  - title: github
    url: https://github.com/ATGenomics

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
